<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="formulaparser_tests.ParserTest-20170423031207" skipped="0" tests="2" time="0.003">
	<testcase classname="formulaparser_tests.ParserTest" name="testParseMatrix" time="0.000"/>
	<testcase classname="formulaparser_tests.ParserTest" name="testParseExpression" time="0.002">
		<error message="'list' object has no attribute 'matrix'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/hyttijan/MatrixCalculator/src/unittest/python/formulaparser_tests.py", line 14, in testParseExpression
    self.assertEqual(invertedMatrix.matrix[0],[-0.3529411764705882,0.47058823529411764, 0.2941176470588235])
AttributeError: 'list' object has no attribute 'matrix'
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
